# Generated by Django 2.2.15 on 2020-08-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="jhgjgkgjhgjh",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
