# Generated by Django 2.2.15 on 2020-08-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_jhgjgkgjhgjh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='jhgjgkgjhgjh',
        ),
    ]
